---
title: "Teaching"
---

[Ch 1](https://zandergordan.com/lectures/Fall2025/Ch1%20Mankiws%2010%20Principles.html)

[Ch 2](https://www.zandergordan.com/lectures/Fall2025/Ch%202%20Thinking%20Like%20an%20Economist.html)

[Ch 3](/lectures/Fall2025/ch3.pptx)

[Ch 4](/lectures/Fall2025/ch4.pptx)

<details>

<summary>Morning Micro</summary>

[Ch 5](/lectures/Fall2025/ch5micro.pptx)

[Ch 6](/lectures/Fall2025/ch6micro.pptx)

</details>

<details>

<summary>Afternoon Micro</summary>

As discussed, we will be doing a simplified grading scheme for the rest of the semester since I am taking over part way through. We have 4 unit exams (15 points each, schedule below), and a final exam (30 points), as well as periodic exit tickets (10 points), which are mini in class assignments, submitted in class through a link I will show on the board with a QR code.

Schedule:

Week 3: [Ch 5](/lectures/Fall2025/ch5micro.pptx) on elasticity

Week 4: [Ch 6](/lectures/Fall2025/ch6micro.pptx) on price controls and taxes

Week 5, Sep 15 to 19: Exam on Tuesday, then Ch 7 on Consumer and Producer surplus

Week 6, Sep 22 to 26: Ch 8 on Costs of Taxation

Week 7, Sep 29 to Oct 3: Ch 9 on international trade

Week 8, Oct 6 to 10: Exam on Tuesday, then Ch 10 on Externalities

Week 9, Oct 13 to 17: Ch 11 on Public Goods

Week 10, Oct 20 to 24: Ch 13 on Tax Systems

Week 11, Oct 27 to 31: Exam on Tuesday, then Ch 14 on Production Costs

Week 12, Nov 3 to 7: Ch 15 on Competition

Week 13, Nov 10 to 14: Ch 16 on Monopoly

Week 14, Nov 17 to 21: Ch 17 and 18 on monopolistic competition and oligopoly

Week 15, Nov 24 to 28: Exam on Tuesday

Week 16, Dec 1 to 5: Ch19-21 on Inequality

</details>

<details>

<summary>Macro</summary>

[Ch 5](/lectures/Fall2025/ch5macro.pptx)

[Ch 6](/lectures/Fall2025/ch6macro.pptx)

</details>
