---
title: "Wednesdays #1"
author: "Zander Gordan"
date: "2026-01-14"
categories: [life, religion]
---

Today's post is intended as a first in a weekly series on the topic of wisdom, done on Wednesdays due to the etymological connection with Woden/Odin. I read the first few chapters of [The Wisdom of No Escape](https://www.goodreads.com/work/quotes/1582074-the-wisdom-of-no-escape-and-the-path-of-loving-kindness) earlier today, which I had been meaning to get around to for some while. The part which sounded especially appealing was as follows "Meditation practice isn't about trying to throw ourselves away and become something better. It's about befriending who we are already." Though I still don't know if I am ready to commit to a serious meditation practice, I am having enough trouble keeping up with an exercise routine.

Even without meditation, there is something to be gleaned from the book, so I thought I would pass it along with my recommendation. Probably it will warrant a re-read to more fully integrate the ideas, but it is a very accessible entry point for Buddhist thinking, at least to me.
