---
title: "On The Shohei Deal"
author: "Zander Gordan"
date: "2023-12-11"
categories: [sports, economics]
---

It is generally agreed that a dollar today is worth more than a dollar tomorrow. There are a number of reasons for this, the ones I would focus on are inflation, investments, and the value of spending money earlier in our life as opposed to when we are in our old age. Economists often speak of this idea by referring to the "time value of money."

Given the last couple years of inflation we have experienced, I think everyone understands the time value of money in the sense that you could have bought more stuff for the same amount of money a few years ago than you could get now. But an even more fundamental aspect of the time value of money has to do with investment opportunities. If you can take your money and put it to productive use by running a business, or investing in someone elses business, then the profit that you generate while that business is running is the value created by having the money invested in the business. Thus even in an economy with little to no inflation, the time value of money means that a dollar today is worth more than a dollar tomorrow, because the dollar today can be invested to earn a financial return.

I want to talk about what the time value of money means for the recent deal bringing Shohei Ohtani across town to the LA Dodgers. The punchline is that what was initially announced as a \$700 million, 10 year deal, is substantially less impressive than it sounds since the vast majority of the money will be received far in the future. Specifically, [we are now being told](https://theathletic.com/5129506/2023/12/11/dodgers-shohei-ohtani-contract-deferrals/) that Shohei will receive only \$2 million per year for the 10 years he plays under the new contract (2024-2033), and then will receive \$68 million for ten years after (2034-2043). The Athletic article I link to above has this to say about the arrangement: "For the 10 years that he is to play for the Dodgers, then, Ohtani\'s deal could be thought of as being worth \$46 million on average every year. But over the full 20-year lifespan of the deal --- including the following 10 years when the deferrals are paid out, a time when Ohtani is no longer under contract with the team --- he is to make a total of \$700 million."

I thought that this quote might be confusing to some baseball fans with limited economics and finance knowledge, which is the reason I wanted to make this post. Based on what I have written already, hopefully it is clear that the reason the deal can be thought of as only worth \$46 million a year has to do with investments: Shohei would be much better off if they gave him the full \$700 million immediately and then he could invest the money, or even if he was paid \$70 million each year, as I initially thought when I first heard the news this weekend. But I want to provide some context about how exactly the \$46 million figure was reached, and what it means for how you should think about this historic deal.

The \$46 million figure quoted by The Athletic is what's known in baseball as the average annual value (or AAV) of the contract, which may be a familiar term to baseball fans who follow the sport closely. In most contracts, the AAV is simply the average value of the contract, so a 2 year contract that paid \$10 million in the first year and then \$20 million in the second would have an AAV of \$15 million. But the calculation becomes more complicated for the Shohei deal, because of the deferrals, or money that is paid after the year in which the player worked. In this case, the AAV is calculated using an economic concept known as Net Present Value (or NPV), which accounts for the time value of money.

NPV is defined as an amount of money that you could give someone right now, that would be equivalent to the cash flow received over time, given certain assumptions about how the money could be invested. Let me illustrate this with the simplest example possible: say that you have a high yield savings account that pays 10% interest per year, so if you put \$100 in it on New Years Day, then at the end of the year you will have \$110. In this case, if someone offers you a contract that pays out \$110 at the end of the year, you would be just as well off going with a different contract that paid \$100 at the start of the year. Even though the dollar value of one contract is higher, their NPV is the same due to the time value of money.

In baseball, the contracts are much more complex, and pay out different amounts of money over various time periods. Shohei's deal is particularly complex because of the deferrals. But the core concept of NPV is the same when analyzing these contracts no matter how complex they are: the NPV of the contract is the amount that the player could be paid immediately, which would be worth the same as the money they receive over the course of the years of their contract, when we assume that the player could invest their money to earn a certain interest rate.

For those who like numbers and formulas, here is the formula for NPV (others can skip over this):

$$
NPV = \sum_{t=0}^T \frac{P_t}{(1+r)^t}
$$

Where $P_t$ is the payment in year $t$, and $r$ is the interest rate (10% or 0.1 in my earlier example). In year 0, when the contract begins, any money paid immediately is worth the full amount. But as the years go by, the money paid in future years is worth less in NPV terms because we forfeit the opportunity to invest and grow our money in the foregoing years.

```{=html}
<iframe width="800" height="400" src="https://docs.google.com/spreadsheets/d/e/2PACX-1vQhcp4ff0ZDxRh4BHrC5oQjfmB7UsQW8KfTajvwieJ1AeJ67GmTfbwqFeKYlLVDFxrS-F7_QwGGsC29/pubhtml?widget=true&amp;headers=false"></iframe>
```
In the spreadsheet above, I show the calculations of NPV for the entire Shohei deal, as well as for the AAV calculation. Let's break it down. Starting on the right side of the sheet, which shows the AAV calculation: Shohei will receive \$2 million each year that he plays, then for 9 years after that will not receive any more compensation for that year of play, until finally after 10 years he receives the \$68 million he is owed. Based on this schedule of payments, I use the [Google Sheets NPV function](https://support.google.com/docs/answer/3093184?hl=en) to calculate an AAV of \$44 million (I am not sure why I come to a slightly different value than The Athletic, but the figures are close enough). What you can not see in the spreadsheet is one crucial input to the NPV function, the interest rate. I have used an interest rate of 4.43%, and will discuss that choice of rate in a little bit.

Now on the left side of the sheet, I compare the "\$700 million 10 year" Shohei deal under two different cash flow scenarios: Scenario B, where \$70 million is paid each year for 10 years, AKA what I thought was happening when the deal was announced on Saturday, and Scenario A, the actual deal with heavy deferrals. I have calculated the NPV for both deals, which at a 4.43% interest rate is \$365 million for Scenario A, and \$555 for Scenario B. In other words, the NPV of the actual deal is only 66% of what I thought it was when the deal was initially announced. In the weeks leading up to the deal, I think many people were expecting something like 10 years \$500 million with a conventional payment schedule, and so we can see that in NPV terms the actual deal was much closer to expectations. Still a historic deal, but not quite as record smashing as initially reported.

Now about that interest rate: I have used 4.43% because apparently this is the rate that MLB will use. Lone Star Ball [has covered the issue well](https://www.lonestarball.com/2023/12/11/23996986/deferred-money-mlb-luxury-competitive-balance-tax-shohei-ohtani-los-angeles-dodgers-cba), showing that in the collective bargaining agreement it is stated that the interest rate used for calculating NPV in AAV is the "Federal mid-term rate" as calculated by the IRS, which according to [this document](https://www.irs.gov/pub/irs-drop/rr-23-18.pdf) is 4.43%. Now is a good time to mention that the interest rate to use in these sorts of analyses is a very contentious issue. For instance, the US federal government recently announced that it would change the rate used in its analysis of federal regulations from a range of 3-7% to 2%, and this was [widely commented on](https://www.epi.org/publication/epi-comment-re-proposed-omb-circular-no-a-4-regulatory-analysis/) by many economists and institutions and not without controversy. But even in lower stakes situations such as baseball, it is not always easy to know what rate to use. The problem is related to the concept of financial risk, as you can generally earn a higher interest rate if you are willing to make riskier investments. In essence, if the owners of the Dodgers are willing to take on the necessary risk to earn interest on their investments of greater than 4.43%, then this Shohei deal will mean that the \$45 million AAV is a very good deal for them in terms of avoiding baseball's Competitive Balance Tax.
