---
title: "President's Day Update"
author: "Zander Gordan"
date: "2025-02-17"
categories: [life]
---

Well, despite rumors to the contrary, the blog lives on in 2025.

I continue to reside in Pinellas County, Florida, and despite attempts to escape it does appear at this point that this arrangement will continue into the foreseeable future, however short that may have now become. In any case I am presently enjoying a rare cool evening, with the promise of more to come soon, so I can pretend for a moment that the long Summer is not so menacingly imminent.

The economics career remains presently unchanged, I am a full time researcher moonlighting as an educator. I am thinking that the blog may become an outlet for some pedagogical material, since I simply have nowhere better to put such material.

Musically, I have been turning away from the DAW (Bitwig) lately in favor of practicing an instrument: the [Linnstrument](https://www.rogerlinndesign.com/linnstrument). Piano keyboard meets 8 string bass guitar, I am having a lot of fun with it, and have been more consistent in practicing than I ever was able to be with the keyboard. An underrated feature is that it accommodates a strap to be worn like a guitar, which for some reason makes me much more inclined to use it.

Economic uncertainty has been deterring me from booking travel aside from work travel, though Hannah has some trips in the works. As things firm up over the next few months, so may our travel agenda. So far we are on a 2 year streak with Transatlantic trips, hopefully we can make it a third.

I may have finally managed to become a morning person again, which is what you really ought to be when you live a short walk from brilliant sunrise views.
