---
title: "Weekend Update #2"
author: "Zander Gordan"
date: "2024-03-17"
categories: [life, sports, literature, religion]
---

Happy St. Patrick's day, for another 3 hours at least. As I begin writing, Atlanta United is about to wrap up at 2-0 victory over Orlando, getting a healthy start to the 2024 campaign.

The MLB season will begin on Tuesday, with a break from tradition as the Dodgers and Padres play a 2 game series in Korea, before Opening Day. Hannah will be waking up to watch these games at 6am eastern, I will have to make a game-time decision as to whether I am willing to give up my beauty sleep.

I finished reading my last great book some time ago, which was the Briggs translation of War and Peace. I've decided to embark on a new literary undertaking, which is to get a study bible (HarperCollins) and some other related works and begin familiarizing myself with the Christian tradition. This obviously is a long-term endeavor, and in my opinion not likely to be terribly rewarding on its own, and so my plan is to intersperse this learning with revisiting some of the classics already familiar to me, including especially Shakespeare, and the American Transcendentalists, and to try to appreciate aspects of these works which I may have not when I read them in High School with little to no familiarity with the Bible.
