---
title: "Put Your Money Where Your Mouth Is: Superbowl Conspiracy Edition"
author: "Zander Gordan"
date: "2024-02-11"
categories: [economics, sports, politics]
---

It is presently fashionable in some quarters to insist that today's big game is rigged in favor of the Chiefs (the details do not bear repeating so I will leave it at that). With sports betting now legal in many jurisdictions across the US, I wonder what portion of people who hold this belief are interested in monetizing their insider knowledge.

I just checked my local sports betting app, and the odds ratios are 1.83 for the 49er's and 2.00 for the Chiefs, meaning the 49ers are in fact slightly favored by Vegas, and the app is offering a double-or-nothing proposition for every dollar someone wagers on the Chiefs.

If you are 90+ percent sure that the game is rigged in favor of the Chiefs, what portion of your life savings should you be betting on this incredible chance to double your money instantly?

As a side note, I believe most betting operators have the home address of their customers, and perhaps even some other demographic data. I would love to see an analysis of how wagers for the Chiefs correlate at the voting precinct level with recent election results, among other things. But I do not think Vegas is known for being generous with their data, oh well...
