---
title: "Ode to the Keytar"
author: "Zander Gordan"
date: "2024-01-23"
categories: [music, life]
---

```{=html}
<iframe src="https://drive.google.com/file/d/1IWFMi2ikK06W1stPUEl7rNqFqiXMNuAS/preview" width="640" height="480" allow="autoplay"></iframe>
```
Today I am packing up my keytar, to ship it off to it's buyer. This is in fact the second keytar I have owned, having sold the first one back in I believe 2017. I have fond memories of both models, this one a Korg RK-100S2, which has microKORG-esque presets, and I love the ergonomics of the keytar, allowing me to riff on a melody while walking around my house absent-mindedly.

But, unfortunately I just don't think the keytar fits into my plans for the EBINLO project. I plan on using Eurorack sequencers to create the melodies for EBINLO songs, and frankly my keyboard skills were never all that impressive anyway.

I will at times miss the keytar, but in any case I think it will be best that I get used to using the pads on my Ableton Push for any melodic sequencing outside of the Eurorack; there's just no need for a traditional keyboard in my current setup. As per my last post, I am down to just the modular and the Push, and I want to force myself to really focus on exploring that setup.
