---
title: "On Consistency in the CFP"
author: "Zander Gordan"
date: "2023-12-3"
categories: [sports, economics]
---

I do not believe that the College Football Playoff committee has a consistent system for determining its rankings of the top teams for inclusion in the playoffs.

I am a Florida State fan, so I am obviously biased and outraged by the committee's decision to exclude my team from the playoff. The talking heads on ESPN have today framed the committee's decision in terms of two competing selection criteria: the best teams versus the most deserving teams. But I will argue that the committee has failed to consistently commit to one or the other of these criteria, and what results is a non-transparent, unsatisfying compromise.

Today an undefeated Power 5 conference champion has been left out of the playoffs, in favor of a 1-loss SEC champion. Those who support this decision justify it by saying that it represents a movement by the committee towards truly selecting the best 4 teams, rather than the 4 most deserving teams. They argue, if Alabama were to play FSU next week, who would be considered the favorite? I agree that Alabama would be the favorite. But how consistent has the committee been in applying this logic? Not very, in my opinion.

My case in point is their relative rankings of #2 Washington and #6 Georgia. If UW and UGA were to play next week, who would be favored? I think Georgia is the clear answer. I am not a sports stats guy, so I am not especially confident in that prediction, but that is my understanding. So the committee thinks a 1-loss Alabama gets in over an undefeated (albeit Jordan Travis-less) FSU, but is not willing to go so far as to also knock out undefeated (still Penix-led) Washington in favor of UGA. It's about the 4 best teams, until it isn't. If the college football establishment really wanted to put the 4 best teams in, then a data-driven statistical modelling exercise would be the obvious way to do it. Let Vegas do it! But that won't be happening anytime soon.

So I think the committee is not really pursuing the 4 best teams. But they are also excluding a very deserving FSU team. To better understand what is driving the committee, I think it is useful to consider a counterfactual: what if everything played out as it did this weekend, except Georgia got 1 extra touchdown to get the win over Alabama? Then I think it is clear the rankings would be #1 UGA, #2 UM, #3 UW, #4 FSU, #5 UT. There would be 4 undefeated power 5 champs, and 1-loss big-12 champ Texas. I think in that scenario FSU gets the nod over Texas. But note that if that's true, then the relative ranking of FSU versus Texas was determined by the outcome of the SEC championship. In economics we have a concept called the independence of irrelevant alternatives, which would hold that it is irrational for a contest between third parties to affect your rankings of two other teams. So I think this is another example of how the committee has been inconsistent. Admittedly, we can not observe the counterfactual, and I may be wrong, the committee may have selected Texas in that scenario, but I doubt it.

I think it is clear that the committee is not really attempting to put the best 4 teams in the playoff. And I would argue that that should not be their goal anyway. With an expanded 12 team playoff coming next season, it will be interesting to see if the playoff committee elects to make any changes in their rules and guidelines for selecting the best teams. I think we should all be able to agree that putting the statistically, by-the-numbers best 12 teams into the playoff is not desirable. We would, for instance, want an undefeated SMU or other non power-5 team to have a shot at a playoff berth, and we do not want a playoff picture entirely dominated by the SEC and the Big 10.

I do not have any one particular solution. I would say that we should all think more deeply about what "most deserving" means. If, in the future with Oregon and Washington leaving the Pac-12 we have to consider, say, a 1-loss Pac-12 Champion Arizona team against a couple 2 loss SEC or Big 10 teams for the last playoff spot, which will we think moreso deserves the spot? I think college football could learn something from the UEFA champions league. More objectivity would certainly welcome, though it is challenging to achieve given the large number of teams and conferences, but this is precisely what UEFA deals with as well, though they have the advantage of being able to play more games in a year.

Go Noles.
